deploy_version: 0.1.9
image_tag: latest

applications:
  - name: basics
    image: pennlabs/pennbasics
    cmd:
      - test
      - hi
    secret: basics
    secretMounts:
      - name: basics
        path: /etc/nginx/secrets/cert.pem
        item: cert.pem
    ingress:
      hosts:
        - host: pennbasics.com
          paths: ["/"]
