applications: []
cronjobs: []

image_tag: latest

application-defaults:
  replicas: 1
  pullPolicy: IfNotPresent
  port: 80
  svc_type: ClusterIP

cronjob-defaults:
  restartPolicy: Never
  pullPolicy: IfNotPresent
  successLimit: 1
  failureLimit: 1
