{{- include "setDefaults" . }}

{{- $release := .Release.Name }}
{{- $releasens := .Release.Namespace }}
{{- range .apps }}
{{- $port := .port }}
{{- $app_id := printf "%s-%s" $release .name}}
{{- if .ingress -}}
{{- range .ingress.hosts }}
{{/* Regex to compute the apex domain */}}
{{- $domain := regexFind "[\\w-]+\\.[\\w]+$" .host }}
{{- $name := $domain | replace "." "-" }}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ $name }}
spec:
  secretName: {{ $name }}-tls-{{ $release }}
  dnsNames:
  - {{ $domain | quote }}
  - {{ printf "*.%s" $domain | quote }}
  issuerRef:
    name: {{ .issuer_name }}
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}
{{- end }}
{{ end }}
