{{- $release := .Release.Name }}
{{- $releasens := .Release.Namespace }}
{{- $defaults := .Values.defaults }}
{{- $image_tag := .Values.image_tag }}

{{- range .Values.applications }}
{{- $app_id := printf "%s-%s" $release .name}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $app_id | quote }}
  namespace: {{ $releasens }}
  labels:
    name: {{ $app_id | quote }}
spec:
  replicas: {{ .replicas | default $defaults.replicas }}
  selector:
    matchLabels:
      name: {{ $app_id | quote }}
  template:
    metadata:
      labels:
        name: {{ $app_id | quote }}
    spec:
      containers:
        - name: "worker"
          image: "{{ .image }}:{{ .tag | default $image_tag }}"
          imagePullPolicy: {{ .pullPolicy | default $defaults.pullPolicy }}
          {{- if .cmd }}
          cmd:
          {{- range .cmd }}
            - {{ . }}
          {{- end }}
          {{- end }}
          ports:
            - containerPort: {{ .port | default $defaults.port }}
          {{- if .secret }}
          envFrom:
            - secretRef:
                name: {{ .secret }}
          {{- end }}
          {{- if .secretMounts }}
          volumeMounts:
          {{- range .secretMounts }}
            - name: "{{ .name }}-{{ .item }}"
              mountPath: {{ .path | quote }}
              subPath: {{ .item | quote }}
          {{- end }}
          {{- end }}
          {{- if .extraEnv }}
          env:
          {{- range .extraEnv }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
          {{- end }}
          {{- end }}
      {{- if .secretMounts }}
      volumes:
      {{- range .secretMounts }}
        - name: "{{ .name }}-{{ .item }}"
          secret:
            secretName: {{ .name | quote }}
            items:
              - key: {{ .item | quote }}
                path: {{ .item | quote }}
      {{- end }}
      {{- end }}
{{- end }}
