{{- $release := .Release.name }}
{{- $releasens := .Release.namespace }}
{{- $defaults := .Values.defaults }}

{{- range .Values.applications }}
{{- $app_id := $release "-" .name }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $app_id }}
spec:
  type: {{ .svc_type | default $defaults.svc_type }}
  ports:
    - port: 80
      targetPort: {{ .port | $defaults.port }}
  selector:
    name: {{ $app_id }}
{{- end }}
