{{- $release := .Release.Name }}
{{- $releasens := .Release.Namespace }}
{{- $defaults := .Values.defaults }}

{{- range .Values.applications }}
{{- $app_id := printf "%s-%s" $release .name }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $app_id | quote }}
spec:
  type: {{ .svc_type | default $defaults.svc_type }}
  ports:
    - port: 80
      targetPort: {{ .port | default $defaults.port }}
  selector:
    name: {{ $app_id | quote }}
{{- end }}
